### PR TITLE
ENH: fix about us page formatting

### PR DESCRIPTION
**Pull request by stephull**
Changes:
* Working link to 'Buy Freedom Merch' on navigation bar
* Formatting titles and logo colors
* Change opacity for better visual clarity on 'See Openings'
* Made each image a 'Download Logo' button
* Ability to download images on selected Download Logo

Screenshots:
Screenshot (4376)
Screenshot (4377)
Screenshot (4378)
Screenshot (4379)
Screenshot (4380)

### CODE REVIEW

**Comment by abstudios617** [comment]
Task linked: [CU-3ygdxt9 FE - About Us Updates](https://app.clickup.com/t/3ygdxt9)

**Review by callmejim1226 — APPROVED** [review]
I ran the app through the front end, and checked the code for this ticket implementation. Everything looked fine to me. I have worked on about-us page too and fixed some of the similar stuff with your ticket task, so I'll try to merge this once you merge this to develop branch. Not really sure why is there so many file changes but just make sure the changes that are not asked from your ticket, won't cause an issue. Great work!

**Review by AlamTahmidul — CHANGES_REQUESTED** [review]
- In `src\pages\about-us\index.js`, can you make the `ContactDescriptions` component left-aligned? The phone number and the emails being aligned would be a cleaner look.
- You also spelled "suport" instead of "support"
- Can you capitalize the words  "Team", "Help", "Us", "Support", "Local", and "Businesses"? It would stay consistent with the previous text "We are Hiring".
- The black font color feels too blend in with the background image. Maybe add a highlight effect on the text? Or, change the font color/change the image opacity more?
- Can you also make the button size "See Openings" bigger? You don't have to change this, but instead of "See Openings" would "Open Positions" be more fitting? If not, then you can keep it as it is.
- Can you make the other buttons (i.e. "Download Logo" buttons bigger (should be proportionally the same as the "See Openings" button)?

**Comment by stephull** [comment]
Updates:
Screenshot (4748)
Screenshot (4749)
Screenshot (4750)

**Review by AlamTahmidul — APPROVED** [review]

**Pull request merged**
